services:
  rfid:
    image: rayanabft/rfid:latest
    container_name: rfid
    restart: always
    privileged: true  #  Donne un accès complet au matériel
    network_mode: host  #  Permet l'accès réseau complet (si besoin)
    volumes:
      - /dev:/dev         #  Accès à tous les périphériques (USB, GPIO...)
      - /sys:/sys         #  Pour GPIO et informations système
      - /run:/run         #  Pour certains services système
    environment:
      - PYTHONUNBUFFERED=1


